apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-fetcher
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-fetcher
  template:
    metadata:
      labels:
        app: stock-fetcher
    spec:
      imagePullSecrets:
      - name: harbor-registry-secret
      containers:
      - name: stock-fetcher
        image: harbor.192.168.50.202.nip.io/library/stock-fetcher:v1
        ports:
        - containerPort: 28001
        env:
        - name: TZ
          value: "Asia/Seoul"
---
apiVersion: v1
kind: Service
metadata:
  name: stock-fetcher-svc
spec:
  selector:
    app: stock-fetcher
  ports:
  - port: 80
    targetPort: 28001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stock-fetcher-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: stock.192.168.50.202.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: stock-fetcher-svc
            port:
              number: 80
