apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb:1.8
        ports:
        - containerPort: 8086
        env:
        - name: INFLUXDB_HTTP_FLUX_ENABLED
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
spec:
  selector:
    app: influxdb
  ports:
  - port: 8086
    target_port: 8086
