apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb:1.8  # 로그를 보니 1.8 버전을 쓰시는 것 같아 맞췄습니다
        ports:
        - containerPort: 8086
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
spec:
  selector:
    app: influxdb
  ports:
  - port: 8086
    target_port: 8086
