services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jh_jenkins
    user: root
    privileged: true
    ports:
      - "1301:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Asia/Seoul
    networks:
      - jh-network
    restart: unless-stopped

networks:
  jh-network:
    external: true
